# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='click_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='limit',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
