# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161208_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
